# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('contact', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('volume', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FileExperiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.Experiment')),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.File')),
            ],
        ),
    ]
